# Generated by Django 5.2.8 on 2025-11-25 08:37

import apps.core.utils
import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('lid', models.CharField(blank=True, default=apps.core.utils.long_id, max_length=8, unique=True, verbose_name='lid')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='data')),
                ('lang_learn', models.BooleanField(default=True, verbose_name='about language')),
                ('src_lang', models.CharField(blank=True, max_length=10, verbose_name='source language')),
                ('lang_learn_lang', models.CharField(blank=True, max_length=10, verbose_name='target language')),
                ('lang_learn_cefr_level_min', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'A1'), (2, 'A2'), (3, 'B1'), (4, 'B2'), (5, 'C1'), (6, 'C2')], null=True, verbose_name='CEFR min')),
                ('lang_learn_cefr_level_max', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'A1'), (2, 'A2'), (3, 'B1'), (4, 'B2'), (5, 'C1'), (6, 'C2')], null=True, verbose_name='CEFR max')),
                ('age_min', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='minimum age')),
                ('age_max', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='maximum age')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['lid'], name='exercise_lid_idx')],
            },
        ),
    ]
