# Generated by Django 5.2.8 on 2025-11-25 19:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0002_exercise"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("text", 0), ("video", 1), ("exercise", 2)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                    2: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("education.Exercise",),
                        {},
                    ),
                },
                verbose_name="Content",
            ),
        ),
    ]
