# Generated by Django 5.2.8 on 2025-11-26 07:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0003_unitpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("text", 0), ("video", 1), ("exercise", 2), ("testu", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: ("apps.core.blocks.VideoBlock", (), {}),
                    2: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("education.Exercise",),
                        {},
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "E.g.: https://www.testu.eu/exercise/i2E4S6T"},
                    ),
                },
                verbose_name="Content",
            ),
        ),
    ]
