# Generated by Django 5.2.8 on 2025-11-26 13:53

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0004_alter_unitpage_body"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.RemoveField(model_name="unitpage", name="description"),
        migrations.RemoveField(model_name="unitpage", name="name"),
        migrations.CreateModel(
            name="ExercisePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "exercise",
                    wagtail.fields.StreamField(
                        [("exercise", 2)],
                        block_lookup={
                            0: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                ("education.Exercise",),
                                {"required": False},
                            ),
                            1: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "E.g.: https://www.testu.eu/exercise/i2e4s6t",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("exercise", 0), ("testu_link", 1)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
