# Generated by Django 5.2.8 on 2025-11-28 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0005_exercisepage_remove_unitpage_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modulepage",
            name="name",
        ),
    ]
