# Generated by Django 5.2.9 on 2025-12-17 14:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0007_alter_exercise_age_max_alter_exercise_age_min_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("text", 0), ("video", 1), ("pdf", 2)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: ("apps.core.blocks.VideoBlock", (), {}),
                    2: ("wagtail.documents.blocks.DocumentChooserBlock", (), {}),
                },
                verbose_name="Content",
            ),
        ),
    ]
