# Generated by Django 5.2.9 on 2026-01-18 20:32

import apps.education.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0008_alter_unitpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="data",
            field=models.JSONField(
                blank=True,
                default=apps.education.models.empty_data,
                verbose_name="data",
            ),
        ),
    ]
