# Generated by Django 6.0.2 on 2026-02-06 10:43
import json
from uuid import uuid4
import django.db.models.deletion
from django.db import migrations, models
from django.core.serializers.json import DjangoJSONEncoder


def set_exercise_fk(apps, schema_editor):
    Exercise = apps.get_model("education", "Exercise")
    ExercisePage = apps.get_model("education", "ExercisePage")

    for page in ExercisePage.objects.all():
        if page.exercise_streamfield:
            if exercise_data := page.exercise_streamfield[:1]:
                pk = exercise_data[0].value["exercise"].pk
                page.exercise_fk = Exercise.objects.get(pk=pk)
                page.save()


def set_exercise_streamfield(apps, schema_editor):
    ExercisePage = apps.get_model("education", "ExercisePage")
    for page in ExercisePage.objects.all():
        if page.exercise_fk:
            value = {"exercise": page.exercise_fk.pk, "testu_link": ""}
            page.exercise_streamfield = json.dumps(
                [{"id": str(uuid4()), "type": "exercise", "value": value}]
            )
            page.save()


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0010_exercise_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercisepage",
            old_name="exercise",
            new_name="exercise_streamfield",
        ),
        migrations.AddField(
            model_name="exercisepage",
            name="exercise_fk",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="education.exercise",
            ),
        ),
        migrations.RunPython(set_exercise_fk, set_exercise_streamfield),
        migrations.RemoveField(
            model_name="exercisepage",
            name="exercise_streamfield",
        ),
        migrations.RenameField(
            model_name="exercisepage",
            old_name="exercise_fk",
            new_name="exercise",
        ),
    ]
