# Generated by Django 6.0.2 on 2026-02-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_exercisepage_streamfield_to_foreignkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='description',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(help_text='E.g.: M1 U1 01', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(blank=True, help_text='Description of the exercise’s content', max_length=100, verbose_name='title'),
        ),
    ]
