# Generated by Django 5.2.6 on 2025-10-17 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepage",
            old_name="body",
            new_name="hero_text",
        ),
    ]
