# Generated by Django 5.2.9 on 2025-12-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0006_remove_modulepage_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="age_max",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "0"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                    (11, "11"),
                    (12, "12"),
                    (13, "13"),
                    (14, "14"),
                    (15, "15"),
                    (16, "16"),
                    (17, "17"),
                    (18, "18+"),
                ],
                default=18,
                verbose_name="maximum age",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="age_min",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "0"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                    (11, "11"),
                    (12, "12"),
                    (13, "13"),
                    (14, "14"),
                    (15, "15"),
                    (16, "16"),
                    (17, "17"),
                    (18, "18+"),
                ],
                default=0,
                verbose_name="minimum age",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="lang_learn_cefr_level_max",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "A1"),
                    (2, "A2"),
                    (3, "B1"),
                    (4, "B2"),
                    (5, "C1"),
                    (6, "C2"),
                ],
                default=6,
                null=True,
                verbose_name="CEFR max",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="lang_learn_cefr_level_min",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "A1"),
                    (2, "A2"),
                    (3, "B1"),
                    (4, "B2"),
                    (5, "C1"),
                    (6, "C2"),
                ],
                default=1,
                null=True,
                verbose_name="CEFR min",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="lang_learn_lang",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fr", "French"),
                    ("sk", "Slovak"),
                    ("en", "English"),
                    ("eo", "Esperanto"),
                ],
                max_length=10,
                verbose_name="target language",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="src_lang",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fr", "French"),
                    ("sk", "Slovak"),
                    ("en", "English"),
                    ("eo", "Esperanto"),
                ],
                max_length=10,
                verbose_name="source language",
            ),
        ),
    ]
