# Generated by Django 6.0.2 on 2026-02-06 10:30
import re

from django.db import migrations, models

RE = re.compile(r"(.*) ?(M\d U\d \d\d)")


def split_name_title(apps, schema_editor):
    Exercise = apps.get_model("education", "Exercise")
    for exercise in Exercise.objects.all():
        if match := RE.search(exercise.name):
            exercise.title, exercise.name = map(str.strip, match.groups())
            exercise.save()


def merge_name_title(apps, schema_editor):
    Exercise = apps.get_model("education", "Exercise")
    for exercise in Exercise.objects.all():
        exercise.name = " ".join([exercise.title, exercise.name])
        exercise.save()


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0009_alter_exercise_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="The users will only see this name",
                max_length=100,
                verbose_name="title",
            ),
        ),
        migrations.RunPython(split_name_title, merge_name_title),
    ]
