# Generated by Django 6.0.3 on 2026-06-01 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_methodologypage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulepage',
            name='image',
        ),
    ]
