/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmLeaveDialog: typeof import('./src/components/ConfirmLeaveDialog.vue')['default']
    CookieConsent: typeof import('./src/components/CookieConsent.vue')['default']
    CopyTextField: typeof import('./src/components/CopyTextField.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    ExamList: typeof import('./src/components/ExamList.vue')['default']
    ExamListItem: typeof import('./src/components/ExamListItem.vue')['default']
    ExamSubmissions: typeof import('./src/components/ExamSubmissions.vue')['default']
    ExerciseFooterAttributes: typeof import('./src/components/ExerciseFooterAttributes.vue')['default']
    ExerciseListItem: typeof import('./src/components/ExerciseListItem.vue')['default']
    ExerciseSearch: typeof import('./src/components/ExerciseSearch.vue')['default']
    InsertMedia: typeof import('./src/components/InsertMedia.vue')['default']
    LanguageSwitcher: typeof import('./src/components/LanguageSwitcher.vue')['default']
    LikeButton: typeof import('./src/components/LikeButton.vue')['default']
    MainAppBar: typeof import('./src/components/MainAppBar.vue')['default']
    MainFooter: typeof import('./src/components/MainFooter.vue')['default']
    MainMenu: typeof import('./src/components/MainMenu.vue')['default']
    MenuItem: typeof import('./src/components/MenuItem.vue')['default']
    MsgBox: typeof import('./src/components/MsgBox.vue')['default']
    OptionsSelector: typeof import('./src/components/OptionsSelector.vue')['default']
    PlayGapSelect: typeof import('./src/components/PlayGapSelect.vue')['default']
    ReportDialog: typeof import('./src/components/ReportDialog.vue')['default']
    RichContent: typeof import('./src/components/RichContent.vue')['default']
    RichContentImage: typeof import('./src/components/RichContentImage.vue')['default']
    RichContentSound: typeof import('./src/components/RichContentSound.vue')['default']
    SheetEditor: typeof import('./src/components/SheetEditor.vue')['default']
    SheetEditorDrawer: typeof import('./src/components/SheetEditorDrawer.vue')['default']
    SheetReview: typeof import('./src/components/SheetReview.vue')['default']
    Toasts: typeof import('./src/components/Toasts.vue')['default']
    UnitDefault: typeof import('./src/components/UnitDefault.vue')['default']
    UnitMultipleChoice: typeof import('./src/components/UnitMultipleChoice.vue')['default']
    UnitMultipleChoiceCheckbox: typeof import('./src/components/UnitMultipleChoiceCheckbox.vue')['default']
    UnitOpenAnswer: typeof import('./src/components/UnitOpenAnswer.vue')['default']
    UnitOpenAnswerTextField: typeof import('./src/components/UnitOpenAnswerTextField.vue')['default']
    UnitPairing: typeof import('./src/components/UnitPairing.vue')['default']
    Xxx_ConfirmLeaveDialog: typeof import('./src/components/xxx_ConfirmLeaveDialog.vue')['default']
    Xxx_CookieConsent: typeof import('./src/components/xxx_CookieConsent.vue')['default']
    Xxx_ExamList: typeof import('./src/components/xxx_ExamList.vue')['default']
    Xxx_ExamListItem: typeof import('./src/components/xxx_ExamListItem.vue')['default']
    Xxx_ExamSubmissions: typeof import('./src/components/xxx_ExamSubmissions.vue')['default']
    Xxx_ExerciseSearch: typeof import('./src/components/xxx_ExerciseSearch.vue')['default']
    Xxx_InsertMedia: typeof import('./src/components/xxx_InsertMedia.vue')['default']
    Xxx_LanguageSwitcher: typeof import('./src/components/xxx_LanguageSwitcher.vue')['default']
    Xxx_LikeButton: typeof import('./src/components/xxx_LikeButton.vue')['default']
    Xxx_MainAppBar: typeof import('./src/components/xxx_MainAppBar.vue')['default']
    Xxx_MainFooter: typeof import('./src/components/xxx_MainFooter.vue')['default']
    Xxx_MainMenu: typeof import('./src/components/xxx_MainMenu.vue')['default']
    Xxx_MenuItem: typeof import('./src/components/xxx_MenuItem.vue')['default']
    Xxx_MsgBox: typeof import('./src/components/xxx_MsgBox.vue')['default']
    Xxx_OptionsSelector: typeof import('./src/components/xxx_OptionsSelector.vue')['default']
    Xxx_PlayGapSelect: typeof import('./src/components/xxx_PlayGapSelect.vue')['default']
    Xxx_ReportDialog: typeof import('./src/components/xxx_ReportDialog.vue')['default']
    Xxx_Toasts: typeof import('./src/components/xxx_Toasts.vue')['default']
  }
}
