# Generated by Django 5.2.8 on 2025-11-24 15:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_homepage_hero_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="modules",
            field=wagtail.fields.StreamField(
                [("title", 2), ("module", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select a heading size"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                            ],
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 0), ("size", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "page_type": ["education.ModulePage"],
                            "verbose_name": "Module",
                        },
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("module_page", 3)]], {}),
                },
                verbose_name="Modules",
            ),
        ),
    ]
