# Generated by Django 5.2.8 on 2025-11-28 10:21

import apps.core.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_alter_homepage_modules"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="hero_cta",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_cta_link",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="modules",
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_cta",
            field=wagtail.fields.StreamField(
                [("button", 3)],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to display in the button",
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Anchor or link to another website page",
                            "required": False,
                            "validators": [apps.core.blocks.fragment_validator],
                        },
                    ),
                    2: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link to a page", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("url", 1), ("page", 2)]],
                        {"blank": True},
                    ),
                },
            ),
        ),
    ]
