# Generated by Django 5.2.9 on 2026-01-02 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_newsindexpage_newspost"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AboutPage",
            new_name="SimplePage",
        ),
    ]
