# Generated by Django 5.2.10 on 2026-01-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_rename_aboutpage_simplepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspost",
            name="standfirst",
            field=models.TextField(default=""),
        ),
    ]
